### ISSUE TITLE
Availability of the dataset

### ISSUE THREAD

**Issue by vijpandaturtle** [shubham1810/idd3d_kit#2]
Hi @shubham1810 
Thanks for the work. 
Is this dataset available in the public domain? If so where can I find the link?

**Comment by shubham1810** [comment]
Hi,
Yes the dataset can be downloaded from [https://idd.insaan.iiit.ac.in](https://idd.insaan.iiit.ac.in). Please login and get the data. Also, note that some calibration files may be missing due to some data corruptions that we have observed.
